// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mixer_exp_generic_double_s (
        ap_clk,
        ap_rst,
        x,
        ap_return
);


input   ap_clk;
input   ap_rst;
input  [63:0] x;
output  [63:0] ap_return;

wire   [7:0] table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_address0;
wire   [57:0] table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_q0;
wire   [7:0] table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_address0;
wire   [25:0] table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_q0;
wire   [7:0] table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_address1;
wire   [25:0] table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_q1;
wire   [7:0] table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_address0;
wire   [41:0] table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_q0;
wire   [0:0] es_sign_fu_286_p3;
reg   [0:0] es_sign_reg_1116;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] es_sign_reg_1116_pp0_iter1_reg;
reg   [0:0] es_sign_reg_1116_pp0_iter2_reg;
reg   [0:0] es_sign_reg_1116_pp0_iter3_reg;
reg   [0:0] es_sign_reg_1116_pp0_iter4_reg;
reg   [0:0] es_sign_reg_1116_pp0_iter5_reg;
reg   [0:0] es_sign_reg_1116_pp0_iter6_reg;
reg   [0:0] es_sign_reg_1116_pp0_iter7_reg;
reg   [0:0] es_sign_reg_1116_pp0_iter8_reg;
wire   [0:0] icmp_ln18_fu_308_p2;
reg   [0:0] icmp_ln18_reg_1121;
reg   [0:0] icmp_ln18_reg_1121_pp0_iter1_reg;
reg   [0:0] icmp_ln18_reg_1121_pp0_iter2_reg;
reg   [0:0] icmp_ln18_reg_1121_pp0_iter3_reg;
reg   [0:0] icmp_ln18_reg_1121_pp0_iter4_reg;
reg   [0:0] icmp_ln18_reg_1121_pp0_iter5_reg;
reg   [0:0] icmp_ln18_reg_1121_pp0_iter6_reg;
reg   [0:0] icmp_ln18_reg_1121_pp0_iter7_reg;
reg   [0:0] icmp_ln18_reg_1121_pp0_iter8_reg;
wire   [0:0] icmp_ln18_1_fu_314_p2;
reg   [0:0] icmp_ln18_1_reg_1129;
reg   [0:0] icmp_ln18_1_reg_1129_pp0_iter1_reg;
reg   [0:0] icmp_ln18_1_reg_1129_pp0_iter2_reg;
reg   [0:0] icmp_ln18_1_reg_1129_pp0_iter3_reg;
reg   [0:0] icmp_ln18_1_reg_1129_pp0_iter4_reg;
reg   [0:0] icmp_ln18_1_reg_1129_pp0_iter5_reg;
reg   [0:0] icmp_ln18_1_reg_1129_pp0_iter6_reg;
reg   [0:0] icmp_ln18_1_reg_1129_pp0_iter7_reg;
reg   [0:0] icmp_ln18_1_reg_1129_pp0_iter8_reg;
wire  signed [70:0] sext_ln227_fu_364_p1;
reg  signed [70:0] sext_ln227_reg_1135;
wire   [0:0] tmp_fu_368_p3;
reg   [0:0] tmp_reg_1140;
wire  signed [31:0] sext_ln229_1_fu_394_p1;
reg  signed [31:0] sext_ln229_1_reg_1145;
reg   [63:0] m_fix_l_reg_1150;
reg   [0:0] tmp_1_reg_1156;
reg   [0:0] tmp_1_reg_1156_pp0_iter1_reg;
wire   [58:0] trunc_ln255_fu_454_p1;
reg   [58:0] trunc_ln255_reg_1166;
reg   [58:0] trunc_ln255_reg_1166_pp0_iter1_reg;
reg   [58:0] trunc_ln255_reg_1166_pp0_iter2_reg;
reg   [58:0] trunc_ln255_reg_1166_pp0_iter3_reg;
wire   [0:0] icmp_ln309_fu_458_p2;
reg   [0:0] icmp_ln309_reg_1171;
reg   [0:0] icmp_ln309_reg_1171_pp0_iter1_reg;
reg   [0:0] icmp_ln309_reg_1171_pp0_iter2_reg;
reg   [0:0] icmp_ln309_reg_1171_pp0_iter3_reg;
reg   [0:0] icmp_ln309_reg_1171_pp0_iter4_reg;
reg   [0:0] icmp_ln309_reg_1171_pp0_iter5_reg;
reg   [0:0] icmp_ln309_reg_1171_pp0_iter6_reg;
reg   [0:0] icmp_ln309_reg_1171_pp0_iter7_reg;
reg   [0:0] icmp_ln309_reg_1171_pp0_iter8_reg;
reg   [0:0] tmp_10_reg_1179;
reg   [0:0] tmp_10_reg_1179_pp0_iter1_reg;
reg   [0:0] tmp_10_reg_1179_pp0_iter2_reg;
reg   [0:0] tmp_10_reg_1179_pp0_iter3_reg;
reg   [0:0] tmp_10_reg_1179_pp0_iter4_reg;
reg   [0:0] tmp_10_reg_1179_pp0_iter5_reg;
reg   [0:0] tmp_10_reg_1179_pp0_iter6_reg;
reg   [0:0] tmp_10_reg_1179_pp0_iter7_reg;
reg   [0:0] tmp_10_reg_1179_pp0_iter8_reg;
wire   [0:0] icmp_ln309_2_fu_500_p2;
reg   [0:0] icmp_ln309_2_reg_1184;
reg   [0:0] icmp_ln309_2_reg_1184_pp0_iter2_reg;
reg   [0:0] icmp_ln309_2_reg_1184_pp0_iter3_reg;
reg   [0:0] icmp_ln309_2_reg_1184_pp0_iter4_reg;
reg   [0:0] icmp_ln309_2_reg_1184_pp0_iter5_reg;
reg   [0:0] icmp_ln309_2_reg_1184_pp0_iter6_reg;
reg   [0:0] icmp_ln309_2_reg_1184_pp0_iter7_reg;
reg   [0:0] icmp_ln309_2_reg_1184_pp0_iter8_reg;
wire  signed [12:0] r_exp_fu_555_p3;
reg  signed [12:0] r_exp_reg_1194;
reg  signed [12:0] r_exp_reg_1194_pp0_iter4_reg;
reg  signed [12:0] r_exp_reg_1194_pp0_iter5_reg;
reg  signed [12:0] r_exp_reg_1194_pp0_iter6_reg;
reg  signed [12:0] r_exp_reg_1194_pp0_iter7_reg;
reg  signed [12:0] r_exp_reg_1194_pp0_iter8_reg;
reg   [7:0] m_diff_hi_reg_1201;
reg   [7:0] m_diff_hi_reg_1201_pp0_iter5_reg;
reg   [7:0] m_diff_hi_reg_1201_pp0_iter6_reg;
reg   [7:0] Z2_reg_1206;
reg   [7:0] Z2_reg_1206_pp0_iter5_reg;
reg   [7:0] Z2_reg_1206_pp0_iter6_reg;
reg   [7:0] Z2_reg_1206_pp0_iter7_reg;
reg   [7:0] Z3_reg_1213;
reg   [7:0] Z3_reg_1213_pp0_iter5_reg;
wire   [34:0] Z4_fu_620_p1;
reg   [34:0] Z4_reg_1219;
reg   [34:0] Z4_reg_1219_pp0_iter5_reg;
reg   [7:0] Z4_ind_reg_1224;
wire   [35:0] exp_Z4_m_1_fu_659_p2;
reg   [35:0] exp_Z4_m_1_reg_1239;
wire   [42:0] exp_Z3_m_1_fu_665_p4;
reg   [42:0] exp_Z3_m_1_reg_1244;
reg   [19:0] tmp_9_reg_1249;
wire   [43:0] exp_Z2P_m_1_fu_717_p2;
reg   [43:0] exp_Z2P_m_1_reg_1264;
wire   [39:0] tmp_s_fu_723_p4;
reg   [39:0] tmp_s_reg_1269;
reg   [35:0] tmp_3_reg_1274;
reg   [57:0] exp_Z1_reg_1279;
wire   [99:0] mul_ln297_fu_278_p2;
reg   [99:0] mul_ln297_reg_1284;
wire   [63:0] zext_ln114_fu_634_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln119_fu_638_p1;
wire   [63:0] zext_ln138_fu_694_p1;
wire   [63:0] zext_ln292_fu_698_p1;
reg    table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce1_local;
reg    table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local;
reg    table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local;
reg    table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local;
wire   [42:0] mul_ln123_fu_270_p0;
wire   [35:0] mul_ln123_fu_270_p1;
wire   [48:0] mul_ln142_fu_274_p0;
wire   [43:0] mul_ln142_fu_274_p1;
wire   [49:0] mul_ln297_fu_278_p0;
wire   [49:0] mul_ln297_fu_278_p1;
wire   [63:0] data_fu_282_p1;
wire   [10:0] es_exp_fu_294_p4;
wire   [51:0] es_sig_fu_304_p1;
wire   [11:0] zext_ln486_fu_320_p1;
wire   [52:0] e_frac_fu_330_p3;
wire   [53:0] zext_ln221_fu_338_p1;
wire   [53:0] e_frac_1_fu_342_p2;
wire   [53:0] e_frac_3_fu_348_p3;
wire   [60:0] m_frac_l_1_fu_356_p3;
wire   [11:0] m_exp_fu_324_p2;
wire   [10:0] sub_ln229_fu_376_p2;
wire  signed [11:0] sext_ln229_fu_382_p1;
wire   [11:0] select_ln229_fu_386_p3;
wire   [70:0] zext_ln229_fu_398_p1;
wire   [70:0] ashr_ln229_fu_402_p2;
wire   [70:0] shl_ln229_fu_408_p2;
wire   [70:0] m_fix_fu_414_p3;
wire  signed [15:0] m_fix_hi_fu_432_p4;
wire   [63:0] zext_ln230_fu_472_p1;
wire   [63:0] shl_ln230_fu_475_p2;
wire   [63:0] ashr_ln230_fu_480_p2;
wire   [63:0] select_ln230_fu_485_p3;
wire   [70:0] shl_ln2_fu_492_p3;
wire  signed [18:0] shl_ln_fu_505_p3;
wire  signed [30:0] grp_fu_1105_p3;
wire   [17:0] trunc_ln243_fu_532_p1;
wire   [12:0] tmp_9_cast_fu_516_p4;
wire   [0:0] icmp_ln243_fu_535_p2;
wire   [12:0] add_ln243_1_fu_541_p2;
wire   [0:0] tmp_2_fu_525_p3;
wire   [12:0] select_ln243_fu_547_p3;
wire   [70:0] mul_ln249_fu_265_p2;
wire   [57:0] tmp_8_fu_567_p4;
wire   [58:0] and_ln_fu_577_p3;
wire   [58:0] sub_ln255_fu_585_p2;
wire   [9:0] f_Z4_fu_642_p4;
wire   [35:0] zext_ln115_fu_652_p1;
wire   [35:0] zext_ln115_1_fu_655_p1;
wire   [78:0] mul_ln123_fu_270_p2;
wire   [35:0] zext_ln126_1_fu_705_p1;
wire   [35:0] add_ln126_fu_708_p2;
wire   [43:0] zext_ln126_fu_713_p1;
wire   [43:0] zext_ln120_fu_702_p1;
wire   [48:0] exp_Z2_m_1_fu_733_p4;
wire   [92:0] mul_ln142_fu_274_p2;
wire   [50:0] and_ln1_fu_762_p5;
wire   [43:0] zext_ln145_2_fu_776_p1;
wire   [43:0] add_ln145_fu_779_p2;
wire   [51:0] zext_ln145_1_fu_784_p1;
wire   [51:0] zext_ln145_fu_772_p1;
wire   [51:0] exp_Z1P_m_1_l_fu_788_p2;
wire   [49:0] exp_Z1_hi_fu_804_p4;
wire   [49:0] exp_Z1P_m_1_fu_794_p4;
wire   [0:0] xor_ln182_fu_824_p2;
wire   [0:0] and_ln182_1_fu_829_p2;
wire   [0:0] xor_ln18_fu_839_p2;
wire   [0:0] and_ln18_fu_844_p2;
wire   [0:0] and_ln182_fu_834_p2;
wire   [0:0] or_ln185_fu_857_p2;
wire   [63:0] select_ln18_fu_849_p3;
wire   [57:0] add_ln297_fu_871_p2;
wire   [106:0] shl_ln1_fu_876_p3;
wire   [106:0] zext_ln297_2_fu_884_p1;
wire   [106:0] add_ln297_1_fu_887_p2;
wire   [0:0] tmp_5_fu_893_p3;
wire   [12:0] r_exp_1_fu_901_p2;
wire   [12:0] r_exp_2_fu_906_p3;
wire   [2:0] tmp_7_fu_913_p4;
wire   [0:0] icmp_ln309_1_fu_923_p2;
wire   [10:0] trunc_ln336_fu_947_p1;
wire   [51:0] tmp_4_fu_957_p4;
wire   [51:0] tmp_6_fu_967_p4;
wire   [10:0] out_exp_fu_951_p2;
wire   [51:0] select_ln303_fu_977_p3;
wire   [63:0] t_fu_985_p4;
wire   [0:0] or_ln309_fu_929_p2;
wire   [0:0] xor_ln309_fu_1004_p2;
wire   [0:0] and_ln309_fu_999_p2;
wire   [0:0] and_ln309_1_fu_1009_p2;
wire   [0:0] or_ln309_1_fu_1015_p2;
wire   [0:0] xor_ln18_1_fu_1021_p2;
wire   [0:0] xor_ln309_1_fu_1032_p2;
wire   [0:0] or_ln309_2_fu_1043_p2;
wire   [0:0] and_ln309_3_fu_1038_p2;
wire   [0:0] xor_ln309_2_fu_1048_p2;
wire   [0:0] or_ln309_3_fu_1054_p2;
wire   [0:0] and_ln309_4_fu_1060_p2;
wire   [0:0] icmp_ln326_fu_941_p2;
wire   [0:0] and_ln309_2_fu_1026_p2;
wire   [0:0] and_ln309_5_fu_1066_p2;
wire   [63:0] retval_1_fu_1081_p2;
wire   [63:0] retval_1_fu_1081_p4;
wire   [63:0] retval_1_fu_1081_p8;
wire   [63:0] retval_1_fu_1081_p9;
wire   [2:0] retval_1_fu_1081_p10;
wire   [14:0] grp_fu_1105_p1;
wire   [63:0] retval_1_fu_1081_p11;
reg   [63:0] x_int_reg;
wire   [78:0] mul_ln123_fu_270_p00;
wire   [78:0] mul_ln123_fu_270_p10;
wire   [92:0] mul_ln142_fu_274_p00;
wire   [92:0] mul_ln142_fu_274_p10;
wire   [99:0] mul_ln297_fu_278_p00;
wire   [99:0] mul_ln297_fu_278_p10;
wire  signed [2:0] retval_1_fu_1081_p1;
wire   [2:0] retval_1_fu_1081_p3;
wire   [2:0] retval_1_fu_1081_p5;
wire   [2:0] retval_1_fu_1081_p7;
wire    ap_ce_reg;

mixer_exp_generic_double_s_table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_arbkb #(
    .DataWidth( 58 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_address0),
    .ce0(table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local),
    .q0(table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_q0)
);

mixer_exp_generic_double_s_table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_arracud #(
    .DataWidth( 26 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_address0),
    .ce0(table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local),
    .q0(table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_q0),
    .address1(table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_address1),
    .ce1(table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce1_local),
    .q1(table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_q1)
);

mixer_exp_generic_double_s_table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_arradEe #(
    .DataWidth( 42 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_address0),
    .ce0(table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local),
    .q0(table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_q0)
);

mixer_mul_13s_71s_71_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 71 ),
    .dout_WIDTH( 71 ))
mul_13s_71s_71_1_1_U1(
    .din0(r_exp_reg_1194),
    .din1(71'd1636647506585939924452),
    .dout(mul_ln249_fu_265_p2)
);

mixer_mul_43ns_36ns_79_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 43 ),
    .din1_WIDTH( 36 ),
    .dout_WIDTH( 79 ))
mul_43ns_36ns_79_1_1_U2(
    .din0(mul_ln123_fu_270_p0),
    .din1(mul_ln123_fu_270_p1),
    .dout(mul_ln123_fu_270_p2)
);

mixer_mul_49ns_44ns_93_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 49 ),
    .din1_WIDTH( 44 ),
    .dout_WIDTH( 93 ))
mul_49ns_44ns_93_1_1_U3(
    .din0(mul_ln142_fu_274_p0),
    .din1(mul_ln142_fu_274_p1),
    .dout(mul_ln142_fu_274_p2)
);

mixer_mul_50ns_50ns_100_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 50 ),
    .din1_WIDTH( 50 ),
    .dout_WIDTH( 100 ))
mul_50ns_50ns_100_1_1_U4(
    .din0(mul_ln297_fu_278_p0),
    .din1(mul_ln297_fu_278_p1),
    .dout(mul_ln297_fu_278_p2)
);

(* dissolve_hierarchy = "yes" *) mixer_sparsemux_9_3_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h4 ),
    .din0_WIDTH( 64 ),
    .CASE1( 3'h2 ),
    .din1_WIDTH( 64 ),
    .CASE2( 3'h1 ),
    .din2_WIDTH( 64 ),
    .CASE3( 3'h0 ),
    .din3_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 64 ))
sparsemux_9_3_64_1_1_U5(
    .din0(retval_1_fu_1081_p2),
    .din1(retval_1_fu_1081_p4),
    .din2(64'd0),
    .din3(retval_1_fu_1081_p8),
    .def(retval_1_fu_1081_p9),
    .sel(retval_1_fu_1081_p10),
    .dout(retval_1_fu_1081_p11)
);

mixer_mac_muladd_16s_15ns_19s_31_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 31 ))
mac_muladd_16s_15ns_19s_31_4_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(m_fix_hi_fu_432_p4),
    .din1(grp_fu_1105_p1),
    .din2(shl_ln_fu_505_p3),
    .ce(1'b1),
    .dout(grp_fu_1105_p3)
);

always @ (posedge ap_clk) begin
    x_int_reg <= x;
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        Z2_reg_1206 <= {{sub_ln255_fu_585_p2[50:43]}};
        Z2_reg_1206_pp0_iter5_reg <= Z2_reg_1206;
        Z2_reg_1206_pp0_iter6_reg <= Z2_reg_1206_pp0_iter5_reg;
        Z2_reg_1206_pp0_iter7_reg <= Z2_reg_1206_pp0_iter6_reg;
        Z3_reg_1213 <= {{sub_ln255_fu_585_p2[42:35]}};
        Z3_reg_1213_pp0_iter5_reg <= Z3_reg_1213;
        Z4_ind_reg_1224 <= {{sub_ln255_fu_585_p2[34:27]}};
        Z4_reg_1219 <= Z4_fu_620_p1;
        Z4_reg_1219_pp0_iter5_reg <= Z4_reg_1219;
        es_sign_reg_1116 <= data_fu_282_p1[32'd63];
        es_sign_reg_1116_pp0_iter1_reg <= es_sign_reg_1116;
        es_sign_reg_1116_pp0_iter2_reg <= es_sign_reg_1116_pp0_iter1_reg;
        es_sign_reg_1116_pp0_iter3_reg <= es_sign_reg_1116_pp0_iter2_reg;
        es_sign_reg_1116_pp0_iter4_reg <= es_sign_reg_1116_pp0_iter3_reg;
        es_sign_reg_1116_pp0_iter5_reg <= es_sign_reg_1116_pp0_iter4_reg;
        es_sign_reg_1116_pp0_iter6_reg <= es_sign_reg_1116_pp0_iter5_reg;
        es_sign_reg_1116_pp0_iter7_reg <= es_sign_reg_1116_pp0_iter6_reg;
        es_sign_reg_1116_pp0_iter8_reg <= es_sign_reg_1116_pp0_iter7_reg;
        exp_Z1_reg_1279 <= table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_q0;
        exp_Z2P_m_1_reg_1264 <= exp_Z2P_m_1_fu_717_p2;
        exp_Z3_m_1_reg_1244[25 : 0] <= exp_Z3_m_1_fu_665_p4[25 : 0];
exp_Z3_m_1_reg_1244[42 : 35] <= exp_Z3_m_1_fu_665_p4[42 : 35];
        exp_Z4_m_1_reg_1239 <= exp_Z4_m_1_fu_659_p2;
        icmp_ln18_1_reg_1129 <= icmp_ln18_1_fu_314_p2;
        icmp_ln18_1_reg_1129_pp0_iter1_reg <= icmp_ln18_1_reg_1129;
        icmp_ln18_1_reg_1129_pp0_iter2_reg <= icmp_ln18_1_reg_1129_pp0_iter1_reg;
        icmp_ln18_1_reg_1129_pp0_iter3_reg <= icmp_ln18_1_reg_1129_pp0_iter2_reg;
        icmp_ln18_1_reg_1129_pp0_iter4_reg <= icmp_ln18_1_reg_1129_pp0_iter3_reg;
        icmp_ln18_1_reg_1129_pp0_iter5_reg <= icmp_ln18_1_reg_1129_pp0_iter4_reg;
        icmp_ln18_1_reg_1129_pp0_iter6_reg <= icmp_ln18_1_reg_1129_pp0_iter5_reg;
        icmp_ln18_1_reg_1129_pp0_iter7_reg <= icmp_ln18_1_reg_1129_pp0_iter6_reg;
        icmp_ln18_1_reg_1129_pp0_iter8_reg <= icmp_ln18_1_reg_1129_pp0_iter7_reg;
        icmp_ln18_reg_1121 <= icmp_ln18_fu_308_p2;
        icmp_ln18_reg_1121_pp0_iter1_reg <= icmp_ln18_reg_1121;
        icmp_ln18_reg_1121_pp0_iter2_reg <= icmp_ln18_reg_1121_pp0_iter1_reg;
        icmp_ln18_reg_1121_pp0_iter3_reg <= icmp_ln18_reg_1121_pp0_iter2_reg;
        icmp_ln18_reg_1121_pp0_iter4_reg <= icmp_ln18_reg_1121_pp0_iter3_reg;
        icmp_ln18_reg_1121_pp0_iter5_reg <= icmp_ln18_reg_1121_pp0_iter4_reg;
        icmp_ln18_reg_1121_pp0_iter6_reg <= icmp_ln18_reg_1121_pp0_iter5_reg;
        icmp_ln18_reg_1121_pp0_iter7_reg <= icmp_ln18_reg_1121_pp0_iter6_reg;
        icmp_ln18_reg_1121_pp0_iter8_reg <= icmp_ln18_reg_1121_pp0_iter7_reg;
        icmp_ln309_2_reg_1184 <= icmp_ln309_2_fu_500_p2;
        icmp_ln309_2_reg_1184_pp0_iter2_reg <= icmp_ln309_2_reg_1184;
        icmp_ln309_2_reg_1184_pp0_iter3_reg <= icmp_ln309_2_reg_1184_pp0_iter2_reg;
        icmp_ln309_2_reg_1184_pp0_iter4_reg <= icmp_ln309_2_reg_1184_pp0_iter3_reg;
        icmp_ln309_2_reg_1184_pp0_iter5_reg <= icmp_ln309_2_reg_1184_pp0_iter4_reg;
        icmp_ln309_2_reg_1184_pp0_iter6_reg <= icmp_ln309_2_reg_1184_pp0_iter5_reg;
        icmp_ln309_2_reg_1184_pp0_iter7_reg <= icmp_ln309_2_reg_1184_pp0_iter6_reg;
        icmp_ln309_2_reg_1184_pp0_iter8_reg <= icmp_ln309_2_reg_1184_pp0_iter7_reg;
        icmp_ln309_reg_1171 <= icmp_ln309_fu_458_p2;
        icmp_ln309_reg_1171_pp0_iter1_reg <= icmp_ln309_reg_1171;
        icmp_ln309_reg_1171_pp0_iter2_reg <= icmp_ln309_reg_1171_pp0_iter1_reg;
        icmp_ln309_reg_1171_pp0_iter3_reg <= icmp_ln309_reg_1171_pp0_iter2_reg;
        icmp_ln309_reg_1171_pp0_iter4_reg <= icmp_ln309_reg_1171_pp0_iter3_reg;
        icmp_ln309_reg_1171_pp0_iter5_reg <= icmp_ln309_reg_1171_pp0_iter4_reg;
        icmp_ln309_reg_1171_pp0_iter6_reg <= icmp_ln309_reg_1171_pp0_iter5_reg;
        icmp_ln309_reg_1171_pp0_iter7_reg <= icmp_ln309_reg_1171_pp0_iter6_reg;
        icmp_ln309_reg_1171_pp0_iter8_reg <= icmp_ln309_reg_1171_pp0_iter7_reg;
        m_diff_hi_reg_1201 <= {{sub_ln255_fu_585_p2[58:51]}};
        m_diff_hi_reg_1201_pp0_iter5_reg <= m_diff_hi_reg_1201;
        m_diff_hi_reg_1201_pp0_iter6_reg <= m_diff_hi_reg_1201_pp0_iter5_reg;
        m_fix_l_reg_1150 <= {{m_fix_fu_414_p3[70:7]}};
        mul_ln297_reg_1284 <= mul_ln297_fu_278_p2;
        r_exp_reg_1194 <= r_exp_fu_555_p3;
        r_exp_reg_1194_pp0_iter4_reg <= r_exp_reg_1194;
        r_exp_reg_1194_pp0_iter5_reg <= r_exp_reg_1194_pp0_iter4_reg;
        r_exp_reg_1194_pp0_iter6_reg <= r_exp_reg_1194_pp0_iter5_reg;
        r_exp_reg_1194_pp0_iter7_reg <= r_exp_reg_1194_pp0_iter6_reg;
        r_exp_reg_1194_pp0_iter8_reg <= r_exp_reg_1194_pp0_iter7_reg;
        sext_ln227_reg_1135[70 : 7] <= sext_ln227_fu_364_p1[70 : 7];
        sext_ln229_1_reg_1145 <= sext_ln229_1_fu_394_p1;
        tmp_10_reg_1179 <= e_frac_3_fu_348_p3[32'd53];
        tmp_10_reg_1179_pp0_iter1_reg <= tmp_10_reg_1179;
        tmp_10_reg_1179_pp0_iter2_reg <= tmp_10_reg_1179_pp0_iter1_reg;
        tmp_10_reg_1179_pp0_iter3_reg <= tmp_10_reg_1179_pp0_iter2_reg;
        tmp_10_reg_1179_pp0_iter4_reg <= tmp_10_reg_1179_pp0_iter3_reg;
        tmp_10_reg_1179_pp0_iter5_reg <= tmp_10_reg_1179_pp0_iter4_reg;
        tmp_10_reg_1179_pp0_iter6_reg <= tmp_10_reg_1179_pp0_iter5_reg;
        tmp_10_reg_1179_pp0_iter7_reg <= tmp_10_reg_1179_pp0_iter6_reg;
        tmp_10_reg_1179_pp0_iter8_reg <= tmp_10_reg_1179_pp0_iter7_reg;
        tmp_1_reg_1156 <= m_fix_fu_414_p3[32'd70];
        tmp_1_reg_1156_pp0_iter1_reg <= tmp_1_reg_1156;
        tmp_3_reg_1274 <= {{mul_ln142_fu_274_p2[92:57]}};
        tmp_9_reg_1249 <= {{mul_ln123_fu_270_p2[78:59]}};
        tmp_reg_1140 <= m_exp_fu_324_p2[32'd11];
        tmp_s_reg_1269 <= {{table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_q0[41:2]}};
        trunc_ln255_reg_1166 <= trunc_ln255_fu_454_p1;
        trunc_ln255_reg_1166_pp0_iter1_reg <= trunc_ln255_reg_1166;
        trunc_ln255_reg_1166_pp0_iter2_reg <= trunc_ln255_reg_1166_pp0_iter1_reg;
        trunc_ln255_reg_1166_pp0_iter3_reg <= trunc_ln255_reg_1166_pp0_iter2_reg;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local = 1'b1;
    end else begin
        table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local = 1'b1;
    end else begin
        table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local = 1'b1;
    end else begin
        table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce1_local = 1'b1;
    end else begin
        table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce1_local = 1'b0;
    end
end

assign Z4_fu_620_p1 = sub_ln255_fu_585_p2[34:0];

assign add_ln126_fu_708_p2 = (exp_Z4_m_1_reg_1239 + zext_ln126_1_fu_705_p1);

assign add_ln145_fu_779_p2 = (exp_Z2P_m_1_reg_1264 + zext_ln145_2_fu_776_p1);

assign add_ln243_1_fu_541_p2 = (tmp_9_cast_fu_516_p4 + 13'd1);

assign add_ln297_1_fu_887_p2 = (shl_ln1_fu_876_p3 + zext_ln297_2_fu_884_p1);

assign add_ln297_fu_871_p2 = (exp_Z1_reg_1279 + 58'd16);

assign and_ln182_1_fu_829_p2 = (xor_ln182_fu_824_p2 & icmp_ln18_1_reg_1129_pp0_iter8_reg);

assign and_ln182_fu_834_p2 = (icmp_ln18_reg_1121_pp0_iter8_reg & and_ln182_1_fu_829_p2);

assign and_ln18_fu_844_p2 = (xor_ln18_fu_839_p2 & icmp_ln18_reg_1121_pp0_iter8_reg);

assign and_ln1_fu_762_p5 = {{{{Z2_reg_1206_pp0_iter7_reg}, {1'd0}}, {tmp_s_reg_1269}}, {2'd0}};

assign and_ln309_1_fu_1009_p2 = (xor_ln309_fu_1004_p2 & icmp_ln309_1_fu_923_p2);

assign and_ln309_2_fu_1026_p2 = (xor_ln18_1_fu_1021_p2 & or_ln309_1_fu_1015_p2);

assign and_ln309_3_fu_1038_p2 = (xor_ln309_1_fu_1032_p2 & icmp_ln309_reg_1171_pp0_iter8_reg);

assign and_ln309_4_fu_1060_p2 = (xor_ln18_1_fu_1021_p2 & or_ln309_3_fu_1054_p2);

assign and_ln309_5_fu_1066_p2 = (icmp_ln326_fu_941_p2 & and_ln309_4_fu_1060_p2);

assign and_ln309_fu_999_p2 = (or_ln309_fu_929_p2 & icmp_ln309_reg_1171_pp0_iter8_reg);

assign and_ln_fu_577_p3 = {{tmp_8_fu_567_p4}, {1'd0}};

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_return = retval_1_fu_1081_p11;

assign ashr_ln229_fu_402_p2 = $signed(sext_ln227_fu_364_p1) >>> zext_ln229_fu_398_p1;

assign ashr_ln230_fu_480_p2 = $signed(m_fix_l_reg_1150) >>> zext_ln230_fu_472_p1;

assign data_fu_282_p1 = x_int_reg;

assign e_frac_1_fu_342_p2 = (54'd0 - zext_ln221_fu_338_p1);

assign e_frac_3_fu_348_p3 = ((es_sign_fu_286_p3[0:0] == 1'b1) ? e_frac_1_fu_342_p2 : zext_ln221_fu_338_p1);

assign e_frac_fu_330_p3 = {{1'd1}, {es_sig_fu_304_p1}};

assign es_exp_fu_294_p4 = {{data_fu_282_p1[62:52]}};

assign es_sig_fu_304_p1 = data_fu_282_p1[51:0];

assign es_sign_fu_286_p3 = data_fu_282_p1[32'd63];

assign exp_Z1P_m_1_fu_794_p4 = {{exp_Z1P_m_1_l_fu_788_p2[51:2]}};

assign exp_Z1P_m_1_l_fu_788_p2 = (zext_ln145_1_fu_784_p1 + zext_ln145_fu_772_p1);

assign exp_Z1_hi_fu_804_p4 = {{table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_q0[57:8]}};

assign exp_Z2P_m_1_fu_717_p2 = (zext_ln126_fu_713_p1 + zext_ln120_fu_702_p1);

assign exp_Z2_m_1_fu_733_p4 = {{{Z2_reg_1206_pp0_iter6_reg}, {1'd0}}, {tmp_s_fu_723_p4}};

assign exp_Z3_m_1_fu_665_p4 = {{{Z3_reg_1213_pp0_iter5_reg}, {9'd0}}, {table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_q0}};

assign exp_Z4_m_1_fu_659_p2 = (zext_ln115_fu_652_p1 + zext_ln115_1_fu_655_p1);

assign f_Z4_fu_642_p4 = {{table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_q1[25:16]}};

assign grp_fu_1105_p1 = 31'd23637;

assign icmp_ln18_1_fu_314_p2 = ((es_sig_fu_304_p1 == 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln18_fu_308_p2 = ((es_exp_fu_294_p4 == 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln243_fu_535_p2 = ((trunc_ln243_fu_532_p1 != 18'd0) ? 1'b1 : 1'b0);

assign icmp_ln309_1_fu_923_p2 = (($signed(tmp_7_fu_913_p4) > $signed(3'd0)) ? 1'b1 : 1'b0);

assign icmp_ln309_2_fu_500_p2 = ((shl_ln2_fu_492_p3 != sext_ln227_reg_1135) ? 1'b1 : 1'b0);

assign icmp_ln309_fu_458_p2 = (($signed(m_exp_fu_324_p2) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln326_fu_941_p2 = (($signed(r_exp_2_fu_906_p3) < $signed(13'd7170)) ? 1'b1 : 1'b0);

assign m_exp_fu_324_p2 = ($signed(zext_ln486_fu_320_p1) + $signed(12'd3073));

assign m_fix_fu_414_p3 = ((tmp_fu_368_p3[0:0] == 1'b1) ? ashr_ln229_fu_402_p2 : shl_ln229_fu_408_p2);

assign m_fix_hi_fu_432_p4 = {{m_fix_fu_414_p3[70:55]}};

assign m_frac_l_1_fu_356_p3 = {{e_frac_3_fu_348_p3}, {7'd0}};

assign mul_ln123_fu_270_p0 = mul_ln123_fu_270_p00;

assign mul_ln123_fu_270_p00 = exp_Z3_m_1_fu_665_p4;

assign mul_ln123_fu_270_p1 = mul_ln123_fu_270_p10;

assign mul_ln123_fu_270_p10 = exp_Z4_m_1_fu_659_p2;

assign mul_ln142_fu_274_p0 = mul_ln142_fu_274_p00;

assign mul_ln142_fu_274_p00 = exp_Z2_m_1_fu_733_p4;

assign mul_ln142_fu_274_p1 = mul_ln142_fu_274_p10;

assign mul_ln142_fu_274_p10 = exp_Z2P_m_1_fu_717_p2;

assign mul_ln297_fu_278_p0 = mul_ln297_fu_278_p00;

assign mul_ln297_fu_278_p00 = exp_Z1P_m_1_fu_794_p4;

assign mul_ln297_fu_278_p1 = mul_ln297_fu_278_p10;

assign mul_ln297_fu_278_p10 = exp_Z1_hi_fu_804_p4;

assign or_ln185_fu_857_p2 = (and_ln18_fu_844_p2 | and_ln182_fu_834_p2);

assign or_ln309_1_fu_1015_p2 = (and_ln309_fu_999_p2 | and_ln309_1_fu_1009_p2);

assign or_ln309_2_fu_1043_p2 = (icmp_ln309_reg_1171_pp0_iter8_reg | icmp_ln309_1_fu_923_p2);

assign or_ln309_3_fu_1054_p2 = (xor_ln309_2_fu_1048_p2 | and_ln309_3_fu_1038_p2);

assign or_ln309_fu_929_p2 = (icmp_ln309_2_reg_1184_pp0_iter8_reg | icmp_ln309_1_fu_923_p2);

assign out_exp_fu_951_p2 = (trunc_ln336_fu_947_p1 + 11'd1023);

assign r_exp_1_fu_901_p2 = ($signed(r_exp_reg_1194_pp0_iter8_reg) + $signed(13'd8191));

assign r_exp_2_fu_906_p3 = ((tmp_5_fu_893_p3[0:0] == 1'b1) ? r_exp_reg_1194_pp0_iter8_reg : r_exp_1_fu_901_p2);

assign r_exp_fu_555_p3 = ((tmp_2_fu_525_p3[0:0] == 1'b1) ? select_ln243_fu_547_p3 : tmp_9_cast_fu_516_p4);

assign retval_1_fu_1081_p10 = {{{icmp_ln18_reg_1121_pp0_iter8_reg}, {and_ln309_2_fu_1026_p2}}, {and_ln309_5_fu_1066_p2}};

assign retval_1_fu_1081_p2 = ((or_ln185_fu_857_p2[0:0] == 1'b1) ? select_ln18_fu_849_p3 : 64'd0);

assign retval_1_fu_1081_p4 = ((tmp_10_reg_1179_pp0_iter8_reg[0:0] == 1'b1) ? 64'd0 : 64'd9218868437227405312);

assign retval_1_fu_1081_p8 = t_fu_985_p4;

assign retval_1_fu_1081_p9 = 'bx;

assign select_ln18_fu_849_p3 = ((and_ln18_fu_844_p2[0:0] == 1'b1) ? 64'd9223372036854775807 : 64'd9218868437227405312);

assign select_ln229_fu_386_p3 = ((tmp_fu_368_p3[0:0] == 1'b1) ? sext_ln229_fu_382_p1 : m_exp_fu_324_p2);

assign select_ln230_fu_485_p3 = ((tmp_reg_1140[0:0] == 1'b1) ? shl_ln230_fu_475_p2 : ashr_ln230_fu_480_p2);

assign select_ln243_fu_547_p3 = ((icmp_ln243_fu_535_p2[0:0] == 1'b1) ? add_ln243_1_fu_541_p2 : tmp_9_cast_fu_516_p4);

assign select_ln303_fu_977_p3 = ((tmp_5_fu_893_p3[0:0] == 1'b1) ? tmp_4_fu_957_p4 : tmp_6_fu_967_p4);

assign sext_ln227_fu_364_p1 = $signed(m_frac_l_1_fu_356_p3);

assign sext_ln229_1_fu_394_p1 = $signed(select_ln229_fu_386_p3);

assign sext_ln229_fu_382_p1 = $signed(sub_ln229_fu_376_p2);

assign shl_ln1_fu_876_p3 = {{add_ln297_fu_871_p2}, {49'd0}};

assign shl_ln229_fu_408_p2 = sext_ln227_fu_364_p1 << zext_ln229_fu_398_p1;

assign shl_ln230_fu_475_p2 = m_fix_l_reg_1150 << zext_ln230_fu_472_p1;

assign shl_ln2_fu_492_p3 = {{select_ln230_fu_485_p3}, {7'd0}};

assign shl_ln_fu_505_p3 = {{tmp_1_reg_1156_pp0_iter1_reg}, {18'd131072}};

assign sub_ln229_fu_376_p2 = (11'd1023 - es_exp_fu_294_p4);

assign sub_ln255_fu_585_p2 = (trunc_ln255_reg_1166_pp0_iter3_reg - and_ln_fu_577_p3);

assign t_fu_985_p4 = {{{{1'd0}, {out_exp_fu_951_p2}}}, {select_ln303_fu_977_p3}};

assign table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_address0 = zext_ln292_fu_698_p1;

assign table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_address0 = zext_ln138_fu_694_p1;

assign table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_address0 = zext_ln119_fu_638_p1;

assign table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_address1 = zext_ln114_fu_634_p1;

assign tmp_2_fu_525_p3 = grp_fu_1105_p3[32'd30];

assign tmp_4_fu_957_p4 = {{add_ln297_1_fu_887_p2[105:54]}};

assign tmp_5_fu_893_p3 = add_ln297_1_fu_887_p2[32'd106];

assign tmp_6_fu_967_p4 = {{add_ln297_1_fu_887_p2[104:53]}};

assign tmp_7_fu_913_p4 = {{r_exp_2_fu_906_p3[12:10]}};

assign tmp_8_fu_567_p4 = {{mul_ln249_fu_265_p2[70:13]}};

assign tmp_9_cast_fu_516_p4 = {{grp_fu_1105_p3[30:18]}};

assign tmp_fu_368_p3 = m_exp_fu_324_p2[32'd11];

assign tmp_s_fu_723_p4 = {{table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_q0[41:2]}};

assign trunc_ln243_fu_532_p1 = grp_fu_1105_p3[17:0];

assign trunc_ln255_fu_454_p1 = m_fix_fu_414_p3[58:0];

assign trunc_ln336_fu_947_p1 = r_exp_2_fu_906_p3[10:0];

assign xor_ln182_fu_824_p2 = (es_sign_reg_1116_pp0_iter8_reg ^ 1'd1);

assign xor_ln18_1_fu_1021_p2 = (icmp_ln18_reg_1121_pp0_iter8_reg ^ 1'd1);

assign xor_ln18_fu_839_p2 = (icmp_ln18_1_reg_1129_pp0_iter8_reg ^ 1'd1);

assign xor_ln309_1_fu_1032_p2 = (or_ln309_fu_929_p2 ^ 1'd1);

assign xor_ln309_2_fu_1048_p2 = (or_ln309_2_fu_1043_p2 ^ 1'd1);

assign xor_ln309_fu_1004_p2 = (icmp_ln309_reg_1171_pp0_iter8_reg ^ 1'd1);

assign zext_ln114_fu_634_p1 = Z4_ind_reg_1224;

assign zext_ln115_1_fu_655_p1 = f_Z4_fu_642_p4;

assign zext_ln115_fu_652_p1 = Z4_reg_1219_pp0_iter5_reg;

assign zext_ln119_fu_638_p1 = Z3_reg_1213;

assign zext_ln120_fu_702_p1 = exp_Z3_m_1_reg_1244;

assign zext_ln126_1_fu_705_p1 = tmp_9_reg_1249;

assign zext_ln126_fu_713_p1 = add_ln126_fu_708_p2;

assign zext_ln138_fu_694_p1 = Z2_reg_1206_pp0_iter5_reg;

assign zext_ln145_1_fu_784_p1 = add_ln145_fu_779_p2;

assign zext_ln145_2_fu_776_p1 = tmp_3_reg_1274;

assign zext_ln145_fu_772_p1 = and_ln1_fu_762_p5;

assign zext_ln221_fu_338_p1 = e_frac_fu_330_p3;

assign zext_ln229_fu_398_p1 = $unsigned(sext_ln229_1_fu_394_p1);

assign zext_ln230_fu_472_p1 = $unsigned(sext_ln229_1_reg_1145);

assign zext_ln292_fu_698_p1 = m_diff_hi_reg_1201_pp0_iter6_reg;

assign zext_ln297_2_fu_884_p1 = mul_ln297_reg_1284;

assign zext_ln486_fu_320_p1 = es_exp_fu_294_p4;

always @ (posedge ap_clk) begin
    sext_ln227_reg_1135[6:0] <= 7'b0000000;
    exp_Z3_m_1_reg_1244[34:26] <= 9'b000000000;
end

endmodule //mixer_exp_generic_double_s
